name: Matrix
on: push
jobs:
    build:
        continue-on-error: true
        strategy: 
            matrix:
                node-version: [12, 14, 16, 18, 20, 22]
                operating-system: [ubuntu-latest, windows-latest, macos-latest]
                include: 
                    - node-version: 18
                    - operating-system: macos-13
                exclude:
                    - node-version: 22
                    - operating-system: ubuntu-latest
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
